### ISSUE TITLE
Possibility to remap keys?

### ISSUE THREAD

**Issue by Kazhuu** [rhysd/vim-llvm#1]
Hello and thank you for awesome Vim plugin!

I was wondering is it possible to remap buffer specific keys like K to something else? I tried to unmap it but my own mappings get unmapped instead, not the buffer specific K key. For now I simply put `let g:llvm_extends_official = 0` to my .vimrc to disable them.

I also tried to copy key setting line from vim file and modify it but I get following error:
`E117: Unknown function: <SNR>1_goto_definition`

So I guess the function is only defined when extended features are enabled.

**Comment by rhysd** [comment]
9f0610c fixed this. Please add your configuration as follows:

```vim
" define gK for going to definition
autocmd FileType llvm nmap <buffer><silent>gK <Plug>(llvm-goto-definition)
```

**Comment by rhysd** [comment]
BTW `g:llvm_extends_official` disables all features extended by this plugin. Instead please use `g:llvm_ext_no_mapping` not to add mappings.

```vim
let g:llvm_ext_no_mapping = 1
```

**Comment by Kazhuu** [comment]
Could readme me updated about this information? Thanks for your help!
